# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('idade', models.IntegerField(max_length=200)),
                ('sexo', models.TextField()),
            ],
        ),
    ]
